version: '3.8'
services:
  postgresdb:
    image: postgres:latest
    container_name: todos-postgres
    environment:
      POSTGRES_DB: todos
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - mynet

  spring-boot-app:
    image: shopping-list-api
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/postgresdb
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
    networks:
        - mynet


networks:
  mynet:  # Define the existing network
    external: true  # Specify
